spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/credit_me
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      properties:
        format-sql: true
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
